language: python

python:
  - 2.7
  - 3.3
  - 3.4

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - CC=g++-4.8 pip install -e .\[dev\]
  - CC=g++-4.8 pip install git+git://github.com/schwehr/libais.git --upgrade
  - pip install git+git://github.com/SkyTruth/gpsdio.git --upgrade

script:
  - py.test tests --cov gpsdio_nmea_driver --cov-report term-missing

after_success:
  - coveralls

notifications:
  flowdock:
    secure: sSDUIIuldA7tWGqgexf+nmeC/+Htm97bwcPaZOHv2+/c3jKsxUoMMnwkcT3ChqPTEvqs2pGoAYuSDDOWXYUZTpETmZyfECmSqPdfD9nePdqDCum8Q909jlttJWR4jmMuhToNifXdwIkPjnspnLrnxCj92/9/Nx/9uSo/+JfPfE0=
